name: tune_pulse
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  just_audio: ^0.9.36
  flutter_svg: ^2.0.5
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  very_good_infinite_list: ^0.7.1
  glass_kit: ^3.0.0
  audio_waveforms: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/
    - lib/assets/svg/
